<a href="https://colab.research.google.com/github/kxrrym03/AI-Impact-on-Job-Salaries/blob/main/AI_vs_Job_Salaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving ai_jobs_salaries_clean.csv to ai_jobs_salaries_clean.csv

In [ ]:
df = pd.read_csv('ai_jobs_salaries_clean.csv')
df.shape

(71913, 17)

In [ ]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,experience_level_label,employment_type_label,work_mode,salary_outlier_flag,role_family,isco_group_hint
0,2025,EX,FT,Head of Data,348516,USD,348516,US,0,US,M,Executive-level,Full-time,On-site,True,Analytics Manager,Information and communications technology serv...
1,2025,EX,FT,Head of Data,232344,USD,232344,US,0,US,M,Executive-level,Full-time,On-site,False,Analytics Manager,Information and communications technology serv...
2,2025,SE,FT,Data Scientist,145400,USD,145400,US,0,US,M,Senior-level,Full-time,On-site,False,Data Scientist,"Mathematicians, actuaries and statisticians"
3,2025,SE,FT,Data Scientist,81600,USD,81600,US,0,US,M,Senior-level,Full-time,On-site,False,Data Scientist,"Mathematicians, actuaries and statisticians"
4,2025,MI,FT,Engineer,160000,USD,160000,US,100,US,M,Mid-level,Full-time,Remote,False,Other / Unclassified,NaN

In [ ]:
df.tail()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,experience_level_label,employment_type_label,work_mode,salary_outlier_flag,role_family,isco_group_hint
71908,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L,Senior-level,Full-time,Remote,True,Data Scientist,"Mathematicians, actuaries and statisticians"
71909,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L,Mid-level,Full-time,Remote,False,Data Scientist,"Mathematicians, actuaries and statisticians"
71910,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S,Entry-level,Full-time,Remote,False,Data Scientist,"Mathematicians, actuaries and statisticians"
71911,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L,Entry-level,Contract,Remote,False,Data Analyst,Business services and administration managers
71912,2021,SE,FT,Data Scientist,7000000,INR,94665,IN,50,IN,L,Senior-level,Full-time,Hybrid,False,Data Scientist,"Mathematicians, actuaries and statisticians"

In [ ]:
df.isnull().sum()

work_year                     0
experience_level              0
employment_type               0
job_title                     0
salary                        0
salary_currency               0
salary_in_usd                 0
employee_residence            0
remote_ratio                  0
company_location              0
company_size                  0
experience_level_label        0
employment_type_label         0
work_mode                     0
salary_outlier_flag           0
role_family                   0
isco_group_hint           40540
dtype: int64

In [ ]:
df = df.drop('isco_group_hint', axis=1)
df.isnull().sum()

work_year                 0
experience_level          0
employment_type           0
job_title                 0
salary                    0
salary_currency           0
salary_in_usd             0
employee_residence        0
remote_ratio              0
company_location          0
company_size              0
experience_level_label    0
employment_type_label     0
work_mode                 0
salary_outlier_flag       0
role_family               0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

          work_year        salary  salary_in_usd  remote_ratio
count  71913.000000  7.191300e+04   71913.000000  71913.000000
mean    2024.425153  1.617102e+05  151161.252625     24.569271
std        0.721198  2.872868e+05   77329.594122     42.917779
min     2020.000000  1.400000e+04   15000.000000      0.000000
25%     2024.000000  9.640000e+04   96000.000000      0.000000
50%     2025.000000  1.397000e+05  138750.000000      0.000000
75%     2025.000000  1.922000e+05  190315.000000      0.000000
max     2025.000000  3.040000e+07  800000.000000    100.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71913 entries, 0 to 71912
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   work_year               71913 non-null  int64
 1   experience_level        71913 non-null  object
 2   employment_type         71913 non-null  object
 3   job_title               71913 non-null  object
 4   salary                  71913 non-null  int64
 5   salary_currency         71913 non-null  object
 6   salary_in_usd           71913 non-null  int64
 7   employee_residence      71913 non-null  object
 8   remote_ratio            71913 non-null  int64
 9   company_location        71913 non-null  object
 10  company_size            71913 non-null  object
 11  experience_level_label  71913 non-null  object
 12  employment_type_label   71913 non-null  object
 13  work_mode               71913 non-null  object
 14  salary_outlier_flag     71913 non-null  bool
 15  role_family             71913 non-null  object
dtypes: bool(1), int64(4), object(11)
memory usage: 8.3+ MB